spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    generate-ddl: false

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
    redis:
      host: ${REDIS_HOST}
      port: 6379

  session:
    store-type: redis
    redis:
      namespace: chat-bridge:session

server:
  servlet:
    encoding:
      charset: UTF-8
    session:
      cookie:
        path: /
        name: JSESSIONID
        # domain: chat-brain.com
        http-only: true
        secure: true
        same-site: none
      timeout: 3600

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    enabled: false
    path: /api-docs/chat-bridge
  swagger-ui:
    url: /api-docs/chat-bridge/main.json
    path: /v1/chat-bridge/

logging:
  level:
    org.springframework.security: TRACE